package org.match.models;

public enum StatisticType {
    NATIONALITY_DISTRIBUTION,
    NATIONALITY_PERCENTAGE,
    TICKET_TYPE_DISTRIBUTION,
    TICKET_TYPE_PERCENTAGE,
    GATE_OCCUPANCY,
    GATE_OCCUPANCY_PERCENTAGE,
    TRIBUNE_ATTENDANCE,
    TRIBUNE_PERCENTAGE,
    TRIBUNE_DISTRIBUTION,
    BLOC_ATTENDANCE,
    MATCH_ATTENDANCE,
    TOP_ACTIVE_SPECTATORS,
    ENTRY_TIME_MIN,
    ENTRY_TIME_MAX
}
